### PR TITLE
Validate if correlation property is mapped to a message

### PR DESCRIPTION
**Pull request by SzymonPobiega**
Solves #212

### CODE REVIEW

**Comment by SimonCropp** [comment]
Isnt there a work around? Hence doesnt need to be a patch

**Comment by weralabaj** [comment]
Hm... Technically this isn't a valid scenario, so not a bug, so that may not be a patch and can be released with 3.0? Only saying that for this particular user that won't help if it's not on 2.x :)

**Comment by SzymonPobiega** [comment]
Yeah, technically it this does not solve anything. It only adds meaningful validation so I guess we can apply it only to the latest.

**Comment by weralabaj** [comment]
rebased

**Pull request merged**
