### PR TITLE
BLOCKED: add netcore build

### PR DESCRIPTION
**Pull request by SimonCropp**

### CODE REVIEW

**Comment by DavidBoike** [comment]
@SimonCropp After merging a couple PRs I kicked the build on this since a couple Oracle acceptance tests have a heisenbug.

What's the status with this? Is this really all that's necessary for the netstandard build?

**Comment by SimonCropp** [comment]
i moved this to blocked until the sql transport is done

**Comment by SzymonPobiega** [comment]
@SimonCropp is alpha build enough to unblock this?

**Comment by SimonCropp** [comment]
@SzymonPobiega it would be. is it on nuget?

**Comment by SimonCropp** [comment]
sorry. myget

**Comment by SzymonPobiega** [comment]
Not yet. But with a single flaky test failing I think I can try to push it.

**Comment by SimonCropp** [comment]
Sounds good. Let me know

**Comment by SzymonPobiega** [comment]
An alpha package is on myget.

**Pull request closed without merging**
