### PR TITLE
Hotfix 3.0.6 (2 issues)

### PR DESCRIPTION
**Pull request by SzymonPobiega**
Based on customer bug report https://c.eu1.visual.force.com/apex/Case?num=00035182

### CODE REVIEW

**Comment by DavidBoike** [comment]
@SzymonPobiega I added the fix for https://github.com/Particular/NServiceBus.Persistence.Sql/pull/263 to this PR. You can't formally review since you opened the, but could you give my work a once-over?

**Comment by DavidBoike** [comment]
BTW, I'm making the assumption that a V5 subscriber (with null endpoint) should never overwrite a filled in subscriber, otherwise a competing V5 and V6 endpoint would continuously flip-flop the subscription table.

**Comment by SzymonPobiega** [comment]
LGTM

**Comment by SzymonPobiega** [comment]
@tmasternak do you want to give it a try?

**Pull request merged**
