### PR TITLE
Feature multi tenancy

### PR DESCRIPTION
**Pull request by markgould**
This is an example showing how multi tenancy might be implemented (See issue #320). 

Another option I looked into was replacing the ISynchronizedStorage and ISynchronizedStorageAdapter implementations, but that is not trivial at the moment, but might be better.

If a single endpoint needs to support multiple tenants using a database-per-tenant architecture, the connection builder needs context information from the incoming message, to read a TenantId or something similar from the message header.

Installers, and the outbox cleaner would not be supported in this scenario without significant changes, and would require knowing all tenant configuration upfront. 

Also, if you are using a transport that doesn't provide native timeout support (Such as SqlTransport), then these will need to be in a shared database (which is already supported) as the timeouts are queried outside of the message context.

Example usage:

Behavior:

```c#
class PropagateIncomingTenantIdBehavior :
	Behavior<ITransportReceiveContext>
{
	public override Task Invoke(ITransportReceiveContext context, Func<Task> next)
	{
	    #region PropagateTenantId
	    
	    if (context.Message.Headers.TryGetValue("TenantId", out var tenant))
	    {
	        context.Extensions.Set("TenantId", tenant);
	    }
	
	    return next();
	
	    #endregion
	}
}
```

Persistence Setup:

```c#
var persistence = endpointConfiguration.UsePersistence<SqlPersistence>();
persistence.ConnectionBuilder(BuildConnection);
persistence.DisableInstaller();
var outbox = endpointConfiguration.EnableOutbox();
outbox.DisableCleanup();
var pipeline = endpointConfiguration.Pipeline;
pipeline.Register(typeof(PropagateIncomingTenantIdBehavior), "Sets the tenant header on the context bag.");
```

Connection Builder:
```c#
private static DbConnection BuildConnection(ContextBag context)
{
    if (context.TryGet<string>("TenantId", out var tenantId))
    {
         //Do Something here
    } 
    return new SqlConnection("connection");
}
```

### CODE REVIEW

**Comment by DavidBoike** [comment]
Hey Mark! Thanks for the PR!

We're definitely interested in better supporting multi-tenant scenarios. I've raised this PR as a point of discussion for the group responsible.

If you're curious why the test checks failed, it's because of the public API approver. Looks like perhaps quite a few public APIs had to change in order to make this work? Starting immediately, I see, with the ConnectionBuilder to add the ContextBag to the connectionBuilder Func. In order to get that to pass, you have to run that test, and then commit the results of the new API with the code. But then we see the change to APIApprovals.txt and know whether by SemVer standards it could be shipped as a patch, minor, or major release.

I can't make any promises about how quickly we can deal with this, but with breaking changes it could only be a new major release, which would make it even more difficult to ship. Since I haven't dug into it at length, do you think it's possible to release it as a minor, meaning only additive APIs, where parameterless connectionBuilders would, for example, still work? (Not that I want you to rush into trying to make that work, just want to get a gut feeling from you.)

**Comment by markgould** [comment]
The ConnectionBuilder can still take a Func without the ContextBag - so that shouldn't be a breaking change. I just pushed another commit to remove the breaking changes from the ScriptRunner, since that won't have a context anyways. The PR doesn't appear to have updated yet though.

**Comment by markgould** [comment]
@ramonsmits which function is breaking? I added a second function (See SqlPersistenceConfig_Connection.cs) 

The breaking changes are all in non-public classes/methods

**Comment by ramonsmits** [comment]
@markgould You are right, I didn't inspect the changes thoroughly.  I was a change on a public method of a private class that made me write that comment. I should have expanded the whole change.

**Comment by DavidBoike** [comment]
Hey @markgould, we're tackling this now. I'm closing your PR, but you can track what we're doing in https://github.com/Particular/NServiceBus.Persistence.Sql/pull/337.

We're not going to have the connection builder dependent upon the ContextBag, but instead request the header name that will be used to identify the tenant, and allow the ConnectionBuilder to build a connection based on that.

To deal with the outbox cleanup issue, we're going to expose an API that basically says don't clean up the Outbox, I will do that myself via SQL Agent, which is really more of a natural fit for that kind of task anyway. If you opt in to multi-tenant mode, we'll require this option, throwing an exception if you don't.

But going with the "provide the header" route also gives us the option, in the future, to create an in-process cleanup task that tracks tenant ids being used, and is then able to create connections for that outside the message processing pipeline when there is no ContextBag available.

**Comment by DavidBoike** [comment]
@markgould check out https://discuss.particular.net/t/nservicebus-persistence-sql-4-5-1-minor-release-available/1038

**Comment by markgould** [comment]
Excellent! I'll look at what's involved in upgrading our endpoints soon, thanks!

**Pull request closed without merging**
