### PR TITLE
check conn string for enlist props

### PR DESCRIPTION
**Pull request by SimonCropp**
the [enlist change](https://github.com/Particular/NServiceBus.Persistence.Sql/commit/1c09d6dd6d99bbe3d589521724cc30297ec80569) broke mysql. discovered by smoke testing.

results in a `MySQL Connector/Net does not currently support distributed transactions.`

i dont think we should enlist if the connection string has it toggled off

@SzymonPobiega @danielmarbach thoughts?

also any ideas how to add a test this?

### CODE REVIEW

**Comment by SimonCropp** [comment]
discussed with @SzymonPobiega. the answer is for mysql users to run in a lower transaction mode which he will document.

**Comment by MarcinHoppe** [comment]
@SimonCropp Should this go into 2.1 milestone? It was not released in 2.0, was it?

**Comment by SimonCropp** [comment]
@MarcinHoppe this was not merged. so no milestone

**Comment by MarcinHoppe** [comment]
@SimonCropp Dammit. I am blind even with glasses. Classic PEBCAK case :).

**Comment by SimonCropp** [comment]
@MarcinHoppe  it happens to us all

**Pull request closed without merging**
